config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :students
  root 'home#index'
  get 'home/about'

  get '/login', to: 'login#index'

  resources :students do 
    resources :articles
  end


  # Instead of having defined each method simply use resources
  # get '/articles', to: 'articles#index'
  # get "/articles/:id", to: "articles#show"

  #Alternative to have only specific routes
  # resources :articles, only: [:index, :create]
  # resources :articles, except: [:destroy]

  resources :articles do
    resources :comments
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments
    validates :title, presence:{ message:"Title Cannot be Empty" }
    validates :body, presence:true,length: { minimum: 10 }

    include Visible
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  
  include Visible
end

app/models/student.rb
class Student < ApplicationRecord
    validates :name, presence:{ message:"Name Cannot be Empty" }
    validates :age, inclusion: { in: 1..150, message: 'The age must be between 1 and 150' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.body = params[:article][:body]
    @article.save

    redirect_to :articles
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'articles/new', status: :unprocessable_entity
    end
  end

  def show
    begin
      @article = Article.find(params[:id])
    rescue
      @error = "No Resource Found"
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title,:body,:status)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy!
    redirect_to article_path(params[:article_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:commenter, :body,:status)
    end
end

app/controllers/concerns/Visible.rb
module Visible
    extend ActiveSupport::Concern

    VALID_STATUS = ['public','private','archived']

    included do 
        validates :status, inclusion: { in: VALID_STATUS }
    end

    class_methods do
        # Methods here are directly callable
    end

    def isArchived?
        status == 'archived'
    end

    def getAllStatus
        VALID_STATUS
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end 
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
    def index
        logger.warn params[:student]
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy!

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :age, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/articles/edit.html.erb
<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>
  <%= @article.errors[:title][0]%>

  
  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>

    <%= @article.errors.full_messages_for(:body)[0]%>


  <div>
    <%= form.submit %>
  </div>
  <%end%>

app/views/articles/index.html.erb
<h1>Articles Loaded</h1>
<br/><br/>

<%= link_to 'New Article', new_article_url %>

<ul>
<% for article in @articles %>
    <% unless article.isArchived? %>
        <li>
            <%= article.title%> : <%= article.body%> 
            <a href="<%= article_url(article) %>" >More Info</a>
            <%= link_to article.title,article %>
        </li>
    <% end %>
<% end %>
</ul>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>
  <%= @article.errors[:title][0]%>
  
  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, @article.getAllStatus %>
  </div>

  <br/><br/>
    <%= @article.errors.full_messages_for(:body)[0]%>


  <div>
    <%= form.submit %>
  </div>


  <br/><br/> 

  
  <% if @article.errors.any? %>
  Errors : 
  <br/>
  <%= @article.errors[:title]%>
    <% for errorMessage in @article.errors.full_messages%>
      <div><%= errorMessage %> </div>
    <% end%>
  <% end%>
<% end %>

app/views/articles/show.html.erb
<% if @error %>
    <%= @error%>

<% else %>

    Edit this : <%= link_to 'Edit', edit_article_url(@article)%> 
    <br/>

    Delete this : <%= link_to "Delete", article_path(@article), data: { turbo_method: :delete } %>
    <br/> <br/>

    HERE IS MY DESCRIPTION : <br/>
    Title : <%= @article.title %>
    <br/>
    Description : <%= @article.body%>

    <br/>

    Existing Comments : 
    <%= render @article.comments%>

    <h2>Add a comment:</h2>
    <%= form_with model: [ @article, @article.comments.build ] do |form| %>
    <p>
        <%= form.label :commenter %><br>
        <%= form.text_field :commenter %>
    </p>
    <p>
        <%= form.label :body %><br>
        <%= form.text_area :body %>
    </p>
    <p>
        <%= form.submit %>
    </p>
<% end %>

<%end%>

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p><%= comment.commenter %> : <%= comment.body %>    ---  <%= link_to 'Delete',article_comment_path(@article,comment),data: { turbo_method: :delete }%></p>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :commenter, style: "display: block" %>
    <%= form.text_field :commenter %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :article_id, style: "display: block" %>
    <%= form.text_field :article_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">BlogPost</a>
    
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/students/new">Create Account</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/login">Sign In</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h3>About file</h3>

app/views/home/index.html.erb
<h1>HomePage</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice Ruby Rails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>

  <body>
    <%# adding a common header for all %>
    <%= render 'home/header' %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/views/login/index.html.erb
<div style="max-width:500px;" class="d-flex flex-column mx-auto ">
<h3>Login Page</h3>
<%= form_with(url: login_path, method: :post) do |form| %>
  <% if @errors%>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% @errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, style: "display: block", class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :password, style: "display: block", class: "form-label" %>
    <%= form.text_field :password, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.submit 'Log In' %>
  </div>
<% end %>

</div>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Name:</strong>
    <%= student.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= student.age %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= student.password %>
  </p>

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>

<div id="students">
  <% @students.each do |student| %>
    <%= render student %>
    <p>
      <%= link_to "Show this student", student %>
    </p>
  <% end %>
</div>

<%= link_to "New student", new_student_path %>

app/views/students/new.html.erb
<div style="max-width:500px;" class="d-flex flex-column mx-auto ">
  <h3>Create Account</h3>
  <%= render "form", student: @student %>
  <br/>
  <div>
    <%= link_to "Back to students", students_path %>
  </div>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>